# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import PyQt5

class Ui_testing(object):
    def setupUi(self, testing):
        testing.setObjectName("testing")
        testing.resize(1233, 852)
        self.centralwidget = PyQt5.QtWidgets.QWidget(testing)
        self.centralwidget.setObjectName("centralwidget")
        self.sign_out_pushButton = PyQt5.QtWidgets.QPushButton(self.centralwidget)
        self.sign_out_pushButton.setGeometry(PyQt5.QtCore.QRect(10, 760, 88, 27))
        self.sign_out_pushButton.setObjectName("sign_out_pushButton")
        self.user_label = PyQt5.QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(PyQt5.QtCore.QRect(110, 760, 67, 19))
        self.user_label.setObjectName("user_label")
        self.testing_tabWidget = PyQt5.QtWidgets.QTabWidget(self.centralwidget)
        self.testing_tabWidget.setGeometry(PyQt5.QtCore.QRect(0, 0, 1221, 751))
        self.testing_tabWidget.setObjectName("testing_tabWidget")
        self.login_tab = PyQt5.QtWidgets.QWidget()
        self.login_tab.setObjectName("login_tab")
        self.login_label = PyQt5.QtWidgets.QLabel(self.login_tab)
        self.login_label.setGeometry(PyQt5.QtCore.QRect(10, 20, 67, 17))
        self.login_label.setObjectName("login_label")
        self.password_label = PyQt5.QtWidgets.QLabel(self.login_tab)
        self.password_label.setGeometry(PyQt5.QtCore.QRect(10, 50, 67, 17))
        self.password_label.setObjectName("password_label")
        self.login_lineEdit = PyQt5.QtWidgets.QLineEdit(self.login_tab)
        self.login_lineEdit.setGeometry(PyQt5.QtCore.QRect(80, 20, 171, 25))
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.password_lineEdit = PyQt5.QtWidgets.QLineEdit(self.login_tab)
        self.password_lineEdit.setGeometry(PyQt5.QtCore.QRect(80, 50, 171, 25))
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.sig_in_pushButton = PyQt5.QtWidgets.QPushButton(self.login_tab)
        self.sig_in_pushButton.setGeometry(PyQt5.QtCore.QRect(120, 80, 89, 25))
        self.sig_in_pushButton.setObjectName("sig_in_pushButton")
        self.testing_tabWidget.addTab(self.login_tab, "")
        self.testing_tab = PyQt5.QtWidgets.QWidget()
        self.testing_tab.setObjectName("testing_tab")
        self.question_label = PyQt5.QtWidgets.QLabel(self.testing_tab)
        self.question_label.setGeometry(PyQt5.QtCore.QRect(20, 130, 1151, 81))
        self.question_label.setObjectName("question_label")
        self.answer1_label = PyQt5.QtWidgets.QLabel(self.testing_tab)
        self.answer1_label.setGeometry(PyQt5.QtCore.QRect(20, 230, 841, 19))
        self.answer1_label.setObjectName("answer1_label")
        self.answer2_label = PyQt5.QtWidgets.QLabel(self.testing_tab)
        self.answer2_label.setGeometry(PyQt5.QtCore.QRect(20, 260, 841, 19))
        self.answer2_label.setObjectName("answer2_label")
        self.answer3_label = PyQt5.QtWidgets.QLabel(self.testing_tab)
        self.answer3_label.setGeometry(PyQt5.QtCore.QRect(20, 290, 841, 17))
        self.answer3_label.setObjectName("answer3_label")
        self.answer4_label = PyQt5.QtWidgets.QLabel(self.testing_tab)
        self.answer4_label.setGeometry(PyQt5.QtCore.QRect(20, 320, 841, 19))
        self.answer4_label.setObjectName("answer4_label")
        self.answer1_checkBox = PyQt5.QtWidgets.QCheckBox(self.testing_tab)
        self.answer1_checkBox.setGeometry(PyQt5.QtCore.QRect(880, 230, 92, 25))
        self.answer1_checkBox.setText("")
        self.answer1_checkBox.setObjectName("answer1_checkBox")
        self.answer2_checkBox = PyQt5.QtWidgets.QCheckBox(self.testing_tab)
        self.answer2_checkBox.setGeometry(PyQt5.QtCore.QRect(880, 260, 92, 25))
        self.answer2_checkBox.setText("")
        self.answer2_checkBox.setObjectName("answer2_checkBox")
        self.answer3_checkBox = PyQt5.QtWidgets.QCheckBox(self.testing_tab)
        self.answer3_checkBox.setGeometry(PyQt5.QtCore.QRect(880, 290, 92, 25))
        self.answer3_checkBox.setText("")
        self.answer3_checkBox.setObjectName("answer3_checkBox")
        self.answer4_checkBox = PyQt5.QtWidgets.QCheckBox(self.testing_tab)
        self.answer4_checkBox.setGeometry(PyQt5.QtCore.QRect(880, 320, 92, 25))
        self.answer4_checkBox.setText("")
        self.answer4_checkBox.setObjectName("answer4_checkBox")
        self.answer_pushButton = PyQt5.QtWidgets.QPushButton(self.testing_tab)
        self.answer_pushButton.setGeometry(PyQt5.QtCore.QRect(880, 360, 88, 27))
        self.answer_pushButton.setObjectName("answer_pushButton")
        self.select_test_for_testing_comboBox = PyQt5.QtWidgets.QComboBox(self.testing_tab)
        self.select_test_for_testing_comboBox.setGeometry(PyQt5.QtCore.QRect(20, 60, 371, 27))
        self.select_test_for_testing_comboBox.setObjectName("select_test_for_testing_comboBox")
        self.select_select_test_for_testing_pushButton = PyQt5.QtWidgets.QPushButton(self.testing_tab)
        self.select_select_test_for_testing_pushButton.setGeometry(PyQt5.QtCore.QRect(400, 60, 88, 27))
        self.select_select_test_for_testing_pushButton.setObjectName("select_select_test_for_testing_pushButton")
        self.result_user_label = PyQt5.QtWidgets.QLabel(self.testing_tab)
        self.result_user_label.setGeometry(PyQt5.QtCore.QRect(0, 680, 67, 19))
        self.result_user_label.setObjectName("result_user_label")
        self.testing_tabWidget.addTab(self.testing_tab, "")
        self.result_tab = PyQt5.QtWidgets.QWidget()
        self.result_tab.setObjectName("result_tab")
        self.result_tableView = PyQt5.QtWidgets.QTableView(self.result_tab)
        self.result_tableView.setGeometry(PyQt5.QtCore.QRect(10, 50, 1201, 661))
        self.result_tableView.setObjectName("result_tableView")
        self.open_result_pushButton = PyQt5.QtWidgets.QPushButton(self.result_tab)
        self.open_result_pushButton.setGeometry(PyQt5.QtCore.QRect(10, 20, 88, 27))
        self.open_result_pushButton.setObjectName("open_result_pushButton")
        self.select_result_comboBox = PyQt5.QtWidgets.QComboBox(self.result_tab)
        self.select_result_comboBox.setGeometry(PyQt5.QtCore.QRect(100, 20, 211, 27))
        self.select_result_comboBox.setObjectName("select_result_comboBox")
        self.testing_tabWidget.addTab(self.result_tab, "")
        self.administration_tab = PyQt5.QtWidgets.QWidget()
        self.administration_tab.setObjectName("administration_tab")
        self.select_test_for_create_question_comboBox = PyQt5.QtWidgets.QComboBox(self.administration_tab)
        self.select_test_for_create_question_comboBox.setGeometry(PyQt5.QtCore.QRect(100, 160, 1081, 27))
        self.select_test_for_create_question_comboBox.setObjectName("select_test_for_create_question_comboBox")
        self.create_answer2_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.create_answer2_lineEdit.setGeometry(PyQt5.QtCore.QRect(100, 280, 1041, 27))
        self.create_answer2_lineEdit.setObjectName("create_answer2_lineEdit")
        self.create_answer2_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.create_answer2_label.setGeometry(PyQt5.QtCore.QRect(20, 280, 67, 19))
        self.create_answer2_label.setObjectName("create_answer2_label")
        self.create_question_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.create_question_lineEdit.setGeometry(PyQt5.QtCore.QRect(100, 200, 1041, 27))
        self.create_question_lineEdit.setObjectName("create_question_lineEdit")
        self.create_answer1_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.create_answer1_lineEdit.setGeometry(PyQt5.QtCore.QRect(100, 240, 1041, 27))
        self.create_answer1_lineEdit.setObjectName("create_answer1_lineEdit")
        self.create_answer1_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.create_answer1_label.setGeometry(PyQt5.QtCore.QRect(20, 240, 67, 19))
        self.create_answer1_label.setObjectName("create_answer1_label")
        self.create_answer3_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.create_answer3_lineEdit.setGeometry(PyQt5.QtCore.QRect(100, 320, 1041, 27))
        self.create_answer3_lineEdit.setObjectName("create_answer3_lineEdit")
        self.create_answer4_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.create_answer4_lineEdit.setGeometry(PyQt5.QtCore.QRect(100, 360, 1041, 27))
        self.create_answer4_lineEdit.setObjectName("create_answer4_lineEdit")
        self.create_answer3_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.create_answer3_label.setGeometry(PyQt5.QtCore.QRect(20, 320, 67, 19))
        self.create_answer3_label.setObjectName("create_answer3_label")
        self.create_answer4_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.create_answer4_label.setGeometry(PyQt5.QtCore.QRect(20, 360, 67, 19))
        self.create_answer4_label.setObjectName("create_answer4_label")
        self.create_question_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.create_question_label.setGeometry(PyQt5.QtCore.QRect(20, 200, 67, 19))
        self.create_question_label.setObjectName("create_question_label")
        self.create_question_pushButton = PyQt5.QtWidgets.QPushButton(self.administration_tab)
        self.create_question_pushButton.setGeometry(PyQt5.QtCore.QRect(10, 400, 131, 27))
        self.create_question_pushButton.setObjectName("create_question_pushButton")
        self.line_5 = PyQt5.QtWidgets.QFrame(self.administration_tab)
        self.line_5.setGeometry(PyQt5.QtCore.QRect(0, 540, 1221, 16))
        self.line_5.setFrameShape(PyQt5.QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(PyQt5.QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.create_new_user_pushButton = PyQt5.QtWidgets.QPushButton(self.administration_tab)
        self.create_new_user_pushButton.setGeometry(PyQt5.QtCore.QRect(160, 680, 88, 27))
        self.create_new_user_pushButton.setObjectName("create_new_user_pushButton")
        self.group_user_new_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.group_user_new_label.setGeometry(PyQt5.QtCore.QRect(10, 640, 67, 19))
        self.group_user_new_label.setObjectName("group_user_new_label")
        self.create_new_user_comboBox = PyQt5.QtWidgets.QComboBox(self.administration_tab)
        self.create_new_user_comboBox.setGeometry(PyQt5.QtCore.QRect(90, 640, 251, 27))
        self.create_new_user_comboBox.setObjectName("create_new_user_comboBox")
        self.password_new_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.password_new_label.setGeometry(PyQt5.QtCore.QRect(10, 600, 111, 19))
        self.password_new_label.setObjectName("password_new_label")
        self.password_new_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.password_new_lineEdit.setGeometry(PyQt5.QtCore.QRect(90, 600, 251, 27))
        self.password_new_lineEdit.setObjectName("password_new_lineEdit")
        self.login_new_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.login_new_lineEdit.setGeometry(PyQt5.QtCore.QRect(90, 560, 251, 27))
        self.login_new_lineEdit.setObjectName("login_new_lineEdit")
        self.login_new_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.login_new_label.setGeometry(PyQt5.QtCore.QRect(10, 560, 121, 19))
        self.login_new_label.setObjectName("login_new_label")
        self.create_test_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.create_test_lineEdit.setGeometry(PyQt5.QtCore.QRect(110, 30, 841, 27))
        self.create_test_lineEdit.setObjectName("create_test_lineEdit")
        self.create_create_test_pushButton = PyQt5.QtWidgets.QPushButton(self.administration_tab)
        self.create_create_test_pushButton.setGeometry(PyQt5.QtCore.QRect(10, 30, 88, 27))
        self.create_create_test_pushButton.setObjectName("create_create_test_pushButton")
        self.line = PyQt5.QtWidgets.QFrame(self.administration_tab)
        self.line.setGeometry(PyQt5.QtCore.QRect(403, 550, 20, 171))
        self.line.setFrameShape(PyQt5.QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(PyQt5.QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = PyQt5.QtWidgets.QFrame(self.administration_tab)
        self.line_2.setGeometry(PyQt5.QtCore.QRect(0, 140, 1221, 16))
        self.line_2.setFrameShape(PyQt5.QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(PyQt5.QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = PyQt5.QtWidgets.QFrame(self.administration_tab)
        self.line_3.setGeometry(PyQt5.QtCore.QRect(0, 430, 1221, 16))
        self.line_3.setFrameShape(PyQt5.QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(PyQt5.QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = PyQt5.QtWidgets.QFrame(self.administration_tab)
        self.line_4.setGeometry(PyQt5.QtCore.QRect(0, 70, 1221, 16))
        self.line_4.setFrameShape(PyQt5.QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(PyQt5.QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.delete_test_pushButton = PyQt5.QtWidgets.QPushButton(self.administration_tab)
        self.delete_test_pushButton.setGeometry(PyQt5.QtCore.QRect(10, 100, 88, 27))
        self.delete_test_pushButton.setObjectName("delete_test_pushButton")
        self.select_user_for_delete_comboBox = PyQt5.QtWidgets.QComboBox(self.administration_tab)
        self.select_user_for_delete_comboBox.setGeometry(PyQt5.QtCore.QRect(530, 600, 251, 27))
        self.select_user_for_delete_comboBox.setObjectName("select_user_for_delete_comboBox")
        self.delete_user_pushButton = PyQt5.QtWidgets.QPushButton(self.administration_tab)
        self.delete_user_pushButton.setGeometry(PyQt5.QtCore.QRect(420, 600, 88, 27))
        self.delete_user_pushButton.setObjectName("delete_user_pushButton")
        self.select_test_for_delete_question_comboBox = PyQt5.QtWidgets.QComboBox(self.administration_tab)
        self.select_test_for_delete_question_comboBox.setGeometry(PyQt5.QtCore.QRect(130, 450, 1081, 27))
        self.select_test_for_delete_question_comboBox.setObjectName("select_test_for_delete_question_comboBox")
        self.selec_test_for_create_pushButton_4 = PyQt5.QtWidgets.QPushButton(self.administration_tab)
        self.selec_test_for_create_pushButton_4.setGeometry(PyQt5.QtCore.QRect(10, 510, 121, 27))
        self.selec_test_for_create_pushButton_4.setObjectName("selec_test_for_create_pushButton_4")
        self.select_test_for_create_comboBox_3 = PyQt5.QtWidgets.QComboBox(self.administration_tab)
        self.select_test_for_create_comboBox_3.setGeometry(PyQt5.QtCore.QRect(130, 480, 1081, 27))
        self.select_test_for_create_comboBox_3.setObjectName("select_test_for_create_comboBox_3")
        self.select_test_for_create_question_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.select_test_for_create_question_label.setGeometry(PyQt5.QtCore.QRect(20, 160, 67, 19))
        self.select_test_for_create_question_label.setObjectName("select_test_for_create_question_label")
        self.select_test_for_delete_question_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.select_test_for_delete_question_label.setGeometry(PyQt5.QtCore.QRect(10, 450, 67, 19))
        self.select_test_for_delete_question_label.setObjectName("select_test_for_delete_question_label")
        self.select_question_for_delete_question_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.select_question_for_delete_question_label.setGeometry(PyQt5.QtCore.QRect(10, 480, 67, 19))
        self.select_question_for_delete_question_label.setObjectName("select_question_for_delete_question_label")
        self.delete_test_comboBox = PyQt5.QtWidgets.QComboBox(self.administration_tab)
        self.delete_test_comboBox.setGeometry(PyQt5.QtCore.QRect(110, 100, 1081, 27))
        self.delete_test_comboBox.setObjectName("delete_test_comboBox")
        self.correct_answers_lineEdit = PyQt5.QtWidgets.QLineEdit(self.administration_tab)
        self.correct_answers_lineEdit.setGeometry(PyQt5.QtCore.QRect(1100, 30, 113, 27))
        self.correct_answers_lineEdit.setObjectName("correct_answers_lineEdit")
        self.correct_answers_label = PyQt5.QtWidgets.QLabel(self.administration_tab)
        self.correct_answers_label.setGeometry(PyQt5.QtCore.QRect(976, 30, 111, 20))
        self.correct_answers_label.setObjectName("correct_answers_label")
        self.create_answer3_checkBox = PyQt5.QtWidgets.QCheckBox(self.administration_tab)
        self.create_answer3_checkBox.setGeometry(PyQt5.QtCore.QRect(1150, 320, 92, 25))
        self.create_answer3_checkBox.setText("")
        self.create_answer3_checkBox.setObjectName("create_answer3_checkBox")
        self.create_answer4_checkBox = PyQt5.QtWidgets.QCheckBox(self.administration_tab)
        self.create_answer4_checkBox.setGeometry(PyQt5.QtCore.QRect(1150, 360, 92, 25))
        self.create_answer4_checkBox.setText("")
        self.create_answer4_checkBox.setObjectName("create_answer4_checkBox")
        self.create_answer2_checkBox = PyQt5.QtWidgets.QCheckBox(self.administration_tab)
        self.create_answer2_checkBox.setGeometry(PyQt5.QtCore.QRect(1150, 280, 92, 25))
        self.create_answer2_checkBox.setText("")
        self.create_answer2_checkBox.setObjectName("create_answer2_checkBox")
        self.create_answer1_checkBox = PyQt5.QtWidgets.QCheckBox(self.administration_tab)
        self.create_answer1_checkBox.setGeometry(PyQt5.QtCore.QRect(1150, 240, 92, 25))
        self.create_answer1_checkBox.setText("")
        self.create_answer1_checkBox.setObjectName("create_answer1_checkBox")
        self.testing_tabWidget.addTab(self.administration_tab, "")
        testing.setCentralWidget(self.centralwidget)
        self.menubar = PyQt5.QtWidgets.QMenuBar(testing)
        self.menubar.setGeometry(PyQt5.QtCore.QRect(0, 0, 1233, 24))
        self.menubar.setObjectName("menubar")
        testing.setMenuBar(self.menubar)
        self.statusbar = PyQt5.QtWidgets.QStatusBar(testing)
        self.statusbar.setObjectName("statusbar")
        testing.setStatusBar(self.statusbar)

        self.retranslateUi(testing)
        self.testing_tabWidget.setCurrentIndex(0)
        PyQt5.QtCore.QMetaObject.connectSlotsByName(testing)

    def retranslateUi(self, testing):
        _translate = PyQt5.QtCore.QCoreApplication.translate
        testing.setWindowTitle(_translate("testing", "MainWindow"))
        self.sign_out_pushButton.setText(_translate("testing", "sign out"))
        self.user_label.setText(_translate("testing", "user"))
        self.login_label.setText(_translate("testing", "login"))
        self.password_label.setText(_translate("testing", "password"))
        self.sig_in_pushButton.setText(_translate("testing", "sig in"))
        self.testing_tabWidget.setTabText(self.testing_tabWidget.indexOf(self.login_tab), _translate("testing", "login"))
        self.question_label.setText(_translate("testing", "Question"))
        self.answer1_label.setText(_translate("testing", "answer1"))
        self.answer2_label.setText(_translate("testing", "answer2"))
        self.answer3_label.setText(_translate("testing", "answer3"))
        self.answer4_label.setText(_translate("testing", "answer4"))
        self.answer_pushButton.setText(_translate("testing", "answer"))
        self.select_select_test_for_testing_pushButton.setText(_translate("testing", "select test"))
        self.result_user_label.setText(_translate("testing", "result"))
        self.testing_tabWidget.setTabText(self.testing_tabWidget.indexOf(self.testing_tab), _translate("testing", "testing"))
        self.open_result_pushButton.setText(_translate("testing", "open result"))
        self.testing_tabWidget.setTabText(self.testing_tabWidget.indexOf(self.result_tab), _translate("testing", "result"))
        self.create_answer2_label.setText(_translate("testing", "Answer"))
        self.create_answer1_label.setText(_translate("testing", "Answer"))
        self.create_answer3_label.setText(_translate("testing", "Answer"))
        self.create_answer4_label.setText(_translate("testing", "Answer"))
        self.create_question_label.setText(_translate("testing", "Question"))
        self.create_question_pushButton.setText(_translate("testing", "create a question"))
        self.create_new_user_pushButton.setText(_translate("testing", "create user"))
        self.group_user_new_label.setText(_translate("testing", "group"))
        self.password_new_label.setText(_translate("testing", "password"))
        self.login_new_label.setText(_translate("testing", "login"))
        self.create_create_test_pushButton.setText(_translate("testing", "create a test"))
        self.delete_test_pushButton.setText(_translate("testing", "delete a test"))
        self.delete_user_pushButton.setText(_translate("testing", "delete user"))
        self.selec_test_for_create_pushButton_4.setText(_translate("testing", "delete question"))
        self.select_test_for_create_question_label.setText(_translate("testing", "Test"))
        self.select_test_for_delete_question_label.setText(_translate("testing", "Test"))
        self.select_question_for_delete_question_label.setText(_translate("testing", "Question"))
        self.correct_answers_label.setText(_translate("testing", "correct answers"))
        self.testing_tabWidget.setTabText(self.testing_tabWidget.indexOf(self.administration_tab), _translate("testing", "administration"))


if __name__ == "__main__":
    import sys
    app = PyQt5.QtWidgets.QApplication(sys.argv)
    testing = PyQt5.QtWidgets.QMainWindow()
    ui = Ui_testing()
    ui.setupUi(testing)
    testing.show()
    sys.exit(app.exec_())

